### ISSUE TITLE
サンプルシミュレーションが開始されない

### ISSUE THREAD

**Issue by DaiGuard** [toppers/hakoniwa-single_robot#42]
はじめまして
箱庭にとても興味があり、自分の環境でもぜひ動作させてみたいと思い
箱庭プロトタイプモデルAをREADMEに従ってセットアップしました

しかし、Unityの画面が起動し、開始ボタンを押すと
プロキシサーバーは動き出すのですがUnityシミュレータが開始されません

※下記はその時の操作です
![hakoniwa](https://github.com/toppers/hakoniwa-single_robot/assets/26181834/7d599780-7dd0-478d-a9c6-820c6e6e65e7)

これの原因は何が考えられるでしょうか？
なにか参考になる情報をいただけると助かります

## 動作環境

- Windows 11 23H2
- WSL 2.0.14.0 (kernel 5.15.133.1-1)

**Comment by tmori** [comment]
@DaiGuard さん
お問い合わせありがとうございます！

現象から推測しますと、Windowsのセキュリティ設定のような気がしております。

以下に本現象に対する対処方法を記載しておりますURLがありますので、
ご確認をお願いできますでしょうか。

なお、今回のケースの場合は、`single-robot.exe` という名前が該当します。

https://github.com/toppers/hakoniwa-document/blob/main/troubleshooting/win/README.md#シミュレーション開始したけどロボットが動かない

**Comment by DaiGuard** [comment]
@tmori さん
教えていただきありがとうございます
早速試してみました

ですがうまくいきませんでした
```single-robot.exe```をファイアーウォールから外してみたのですが
うまくいきません

![image](https://github.com/toppers/hakoniwa-single_robot/assets/26181834/32c19c2c-307f-4707-aa4e-5c1b75ace3f6)

![image](https://github.com/toppers/hakoniwa-single_robot/assets/26181834/b945f799-958a-4d94-99cd-41e63d278d87)

これはRTOS側のプログラムが実行されていないのか
Unityシミュレータ側がスタートしていないのか
どちらが原因なのでしょうか？

**Comment by tmori** [comment]
@DaiGuard さん

早速お試しいただきありがとうございます。
なるほど。ファイアウォールの問題ではないということですね。

> これはRTOS側のプログラムが実行されていないのか
> Unityシミュレータ側がスタートしていないのか
> どちらが原因なのでしょうか？
頂いた動画を拝見したところ以下は正常に動作していると思います。

1. Unity起動後、「開始ボタン」が有効化されていることから、Unityと箱庭の間は通信(TCP)が確立できている
2. 「開始ボタン」押下後、端末側に「EV3RT」のロゴが表示されることから、Athrill（マイコンシミュレータ）がプログラムを実行できている

ただ、この後、ロボットが動かないというのは、UnityとAthrillとの間で制御データのやり取りができていない可能性があるかと考えております。

制御データのやり取りは、UDP通信で行っています。
Windows環境の場合は、セキュリティでUDPパケットがブロックされているケースが多いので、頂いた現象も同じものかと考えておりましたが、ちょっと違うようですね。。

もしよろしければ、箱庭のログファイルを添付いただけますと、もう少し詳細な解析ができるかと思っております。

ログ配置場所は、こちらです。

hakoniwa-single_robot/unity/assets/single-robot/Build/hakoniwa_core.log

**Comment by DaiGuard** [comment]
@tmori さん

いろいろアドバイスいただきありがとうございます

いただいた情報から自分でいろいろやってみて自己解決できました。
結果的に私がdockerのインストールをDocker Desktop for WindowsをWSL2ベースで使っていたのが原因のようです。
Docker Desktop for Windows をアンインストールして、WSL2上のUbuntu20.04からDocker Engineをインストールした場合はうまく動作しました

![hakoniwa_3](https://github.com/toppers/hakoniwa-single_robot/assets/26181834/215f9dd1-69e4-498d-927c-180185d57a43)

**Comment by tmori** [comment]
@DaiGuard さん、うまくいってよかったです！！
原因のご連絡もありがとうございます。よくあるケースと思いますので、箱庭のとラブルシューティング集として管理して行きたいと思います。
